version: '3.8'

services:
  # PostgreSQL Database
  postgresql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: cs2_postgres
    environment:
      POSTGRES_DB: cs2_predictions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - cs2_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cs2_predictions"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ClickHouse Analytics Database
  clickhouse:
    build:
      context: ./docker/clickhouse
      dockerfile: Dockerfile
    container_name: cs2_clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
      - "9009:9009"  # Interserver HTTP
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    networks:
      - cs2_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # RabbitMQ Message Broker
  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    container_name: cs2_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "25672:25672" # Erlang distribution
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - cs2_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
  postgres_logs:
    driver: local
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  cs2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16 